# config/zedxone.yaml
# Parameters of the ZED X One node
---
/**:
    ros__parameters:
        
        camera:
            model: 'GS' # Global Shutter: 'GS', 4K HDR: '4K'
            idx: 0
            resolution: 'HD1080' # 'SVGA', 'HD1080', 'HD1200', '4K'
            framerate: 30
            swap_rb: false
            pixel_format: 'COLOR_RGB' # 'COLOR_RGBA', 'COLOR_RGB', 'RAW_BAYER'

        debug:
            grab_verbose_level: 0
            general: false

